(function(){'use strict';
function esc(s){return String(s||'').replace(/[&<>'"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c];});}
function csrf(){var m=document.querySelector('meta[name="csrf-token"]');return m?m.getAttribute('content'):'';}
function key(url){return 'sytvil-link-preview-hidden:'+url;}
function formatDate(ts){if(!ts)return '';try{return new Date(Number(ts)*1000).toLocaleDateString();}catch(e){return '';}}
function controls(el,p){return '<div class="sytvil-link-preview__controls"><button type="button" class="sytvil-lp-refresh" aria-label="Refresh preview">↻ Refresh</button><button type="button" class="sytvil-lp-hide" aria-label="Hide preview">× Hide</button></div>';}
function render(el,data){var p=data.preview||{};var title=p.title||p.url;var provider=p.provider?'<span class="sytvil-link-preview__provider">'+esc(p.provider)+'</span>':'';var fav=p.favicon?'<img class="sytvil-link-preview__favicon" loading="lazy" src="'+esc(p.favicon)+'" alt="">':'';var site='<div class="sytvil-link-preview__site">'+fav+'<span>'+esc(p.siteName||'')+'</span>'+provider+'</div>';
var meta=[];if(p.author)meta.push(esc(p.author));if(p.publishedAt)meta.push(esc(formatDate(p.publishedAt)));if(p.section)meta.push(esc(p.section));var metaHtml=meta.length?'<div class="sytvil-link-preview__meta">'+meta.join(' · ')+'</div>':'';
var img=p.image?'<div class="sytvil-link-preview__image"><img loading="lazy" referrerpolicy="no-referrer" src="'+esc(p.image)+'" alt="" onerror="this.parentNode.style.display=\'none\'"></div>':'';var desc=p.description?'<div class="sytvil-link-preview__description">'+esc(p.description)+'</div>':'';var cls=(p.type==='article'||p.author||p.publishedAt)?' is-article':'';
el.innerHTML='<div class="sytvil-link-preview__shell'+cls+'"><a class="sytvil-link-preview__card" href="'+esc(p.url)+'" target="_blank" rel="noopener noreferrer nofollow">'+img+'<div class="sytvil-link-preview__body">'+site+'<div class="sytvil-link-preview__title">'+esc(title)+'</div>'+metaHtml+desc+'</div></a>'+controls(el,p)+'</div>';el.classList.add('is-loaded');bind(el,p);}
function renderError(el,data){var url=data.url||el.dataset.url;el.innerHTML='<div class="sytvil-link-preview__broken"><div><strong>Preview unavailable</strong><div>'+esc(data.error||'The linked website did not provide a usable preview.')+'</div></div><button type="button" class="sytvil-lp-refresh">Try again</button><button type="button" class="sytvil-lp-hide">Hide</button></div>';bind(el,{url:url});}
function bind(el,p){var refresh=el.querySelector('.sytvil-lp-refresh');if(refresh)refresh.addEventListener('click',function(e){e.preventDefault();refreshPreview(el);});var hide=el.querySelector('.sytvil-lp-hide');if(hide)hide.addEventListener('click',function(e){e.preventDefault();try{localStorage.setItem(key(el.dataset.url),'1');}catch(x){}el.remove();});}
function refreshPreview(el){var endpoint=el.dataset.refreshEndpoint,url=el.dataset.url;if(!endpoint||!url)return;el.innerHTML='<div class="sytvil-link-preview__loading">Refreshing preview…</div>';var body='url='+encodeURIComponent(url);fetch(endpoint,{method:'POST',credentials:'same-origin',headers:{'X-Requested-With':'XMLHttpRequest','Content-Type':'application/x-www-form-urlencoded;charset=UTF-8','X-CSRF-Token':csrf()},body:body}).then(function(r){return r.json();}).then(function(d){if(d&&d.ok)render(el,d);else renderError(el,d||{});}).catch(function(){renderError(el,{url:url,error:'Refresh failed.'});});}
function load(el){if(!el||el.dataset.loaded==='1')return;try{if(localStorage.getItem(key(el.dataset.url))==='1'){el.remove();return;}}catch(e){}el.dataset.loaded='1';var endpoint=el.dataset.endpoint,url=el.dataset.url;if(!endpoint||!url)return;el.innerHTML='<div class="sytvil-link-preview__loading">Loading link preview…</div>';fetch(endpoint+(endpoint.indexOf('?')===-1?'?':'&')+'url='+encodeURIComponent(url),{credentials:'same-origin',headers:{'X-Requested-With':'XMLHttpRequest'}}).then(function(r){return r.json();}).then(function(d){if(d&&d.ok)render(el,d);else renderError(el,d||{url:url});}).catch(function(){renderError(el,{url:url,error:'The preview request failed.'});});}
function scan(root){(root||document).querySelectorAll('.sytvil-link-preview:not([data-loaded="1"])').forEach(load);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){scan(document);});else scan(document);
new MutationObserver(function(ms){ms.forEach(function(m){m.addedNodes.forEach(function(n){if(n.nodeType===1){if(n.matches&&n.matches('.sytvil-link-preview'))load(n);else if(n.querySelectorAll)scan(n);}});});}).observe(document.documentElement,{childList:true,subtree:true});
})();
