<?php
namespace humhub\modules\sytvillinkpreview\services;
use DOMDocument;use DOMXPath;use RuntimeException;
class PreviewFetcher
{
    private int $maxBytes=524288,$maxRedirects=3,$timeout=6;
    public function fetch(string $url):array{
        $url=$this->normalizeUrl($url);if(!DomainPolicy::isAllowed($url))throw new RuntimeException('This domain is not allowed.');$this->assertSafeUrl($url);$current=$url;
        for($r=0;$r<=$this->maxRedirects;$r++){$res=$this->request($current);if($res['redirect']!==null){if($r===$this->maxRedirects)throw new RuntimeException('Too many redirects.');$current=$this->resolveUrl($current,$res['redirect']);if(!DomainPolicy::isAllowed($current))throw new RuntimeException('Redirected domain is not allowed.');$this->assertSafeUrl($current);continue;}$type=strtolower((string)$res['content_type']);if($type!==''&&!str_contains($type,'text/html')&&!str_contains($type,'application/xhtml+xml'))throw new RuntimeException('The URL does not point to an HTML page.');return $this->parseHtml($current,$res['body'],$type);}throw new RuntimeException('Unable to fetch preview.');
    }
    public function assertPublicUrl(string $url):void{$this->assertSafeUrl($this->normalizeUrl($url));}
    private function normalizeUrl(string $url):string{$url=trim(html_entity_decode($url,ENT_QUOTES|ENT_HTML5,'UTF-8'));$p=parse_url($url);if(!is_array($p)||!isset($p['scheme'],$p['host']))throw new RuntimeException('Invalid URL.');$p['scheme']=strtolower($p['scheme']);if(!in_array($p['scheme'],['http','https'],true))throw new RuntimeException('Only HTTP and HTTPS links are supported.');unset($p['fragment']);return $this->buildUrl($p);}
    private function assertSafeUrl(string $url):void{$host=strtolower((string)(parse_url($url,PHP_URL_HOST)?:''));if($host===''||$host==='localhost'||str_ends_with($host,'.localhost'))throw new RuntimeException('Local network URLs cannot be previewed.');if(filter_var($host,FILTER_VALIDATE_IP)){$this->assertPublicIp($host);return;}$ips=@gethostbynamel($host)?:[];if(function_exists('dns_get_record'))foreach(@dns_get_record($host,DNS_A|DNS_AAAA)?:[] as $rec){if(!empty($rec['ip']))$ips[]=$rec['ip'];if(!empty($rec['ipv6']))$ips[]=$rec['ipv6'];}$ips=array_values(array_unique($ips));if(!$ips)throw new RuntimeException('Could not resolve the website address.');foreach($ips as $ip)$this->assertPublicIp($ip);}
    private function assertPublicIp(string $ip):void{if(!filter_var($ip,FILTER_VALIDATE_IP,FILTER_FLAG_NO_PRIV_RANGE|FILTER_FLAG_NO_RES_RANGE))throw new RuntimeException('Private or reserved network addresses cannot be previewed.');}
    private function request(string $url):array{if(!function_exists('curl_init'))throw new RuntimeException('PHP cURL is required for link previews.');$headers=[];$body='';$tooLarge=false;$ch=curl_init($url);curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>false,CURLOPT_FOLLOWLOCATION=>false,CURLOPT_CONNECTTIMEOUT=>3,CURLOPT_TIMEOUT=>$this->timeout,CURLOPT_USERAGENT=>'SytvilLinkPreview/2.0 (+HumHub)',CURLOPT_HTTPHEADER=>['Accept: text/html,application/xhtml+xml;q=0.9,*/*;q=0.1'],CURLOPT_HEADERFUNCTION=>static function($ch,$line)use(&$headers){$len=strlen($line);$line=trim($line);if($line!==''&&str_contains($line,':')){[$n,$v]=explode(':',$line,2);$headers[strtolower(trim($n))]=trim($v);}return $len;},CURLOPT_WRITEFUNCTION=>function($ch,$chunk)use(&$body,&$tooLarge){if(strlen($body)+strlen($chunk)>$this->maxBytes){$remaining=max(0,$this->maxBytes-strlen($body));if($remaining)$body.=substr($chunk,0,$remaining);$tooLarge=true;return 0;}$body.=$chunk;return strlen($chunk);}]);$ok=curl_exec($ch);$err=curl_error($ch);$code=(int)curl_getinfo($ch,CURLINFO_RESPONSE_CODE);$ct=(string)curl_getinfo($ch,CURLINFO_CONTENT_TYPE);curl_close($ch);if($ok===false&&!$tooLarge)throw new RuntimeException($err?:'The website could not be reached.');if($code>=300&&$code<400&&isset($headers['location']))return ['redirect'=>$headers['location'],'body'=>'','content_type'=>$ct];if($code<200||$code>=400)throw new RuntimeException('The website returned HTTP '.$code.'.');return ['redirect'=>null,'body'=>$body,'content_type'=>$ct];}
    private function parseHtml(string $url,string $html,string $ct):array{$old=libxml_use_internal_errors(true);$dom=new DOMDocument();$loaded=@$dom->loadHTML('<?xml encoding="utf-8" ?>'.$html,LIBXML_NOWARNING|LIBXML_NOERROR|LIBXML_NONET);libxml_clear_errors();libxml_use_internal_errors($old);if(!$loaded)throw new RuntimeException('The website metadata could not be parsed.');$xp=new DOMXPath($dom);$meta=[];foreach($xp->query('//meta[@content]')?:[] as $node){$key=strtolower(trim($node->getAttribute('property')?:$node->getAttribute('name')));if($key!==''&&!isset($meta[$key]))$meta[$key]=trim($node->getAttribute('content'));}
        $title=$meta['og:title']??$meta['twitter:title']??'';if($title===''){$n=$xp->query('//title');if($n&&$n->length)$title=trim($n->item(0)->textContent);}$desc=$meta['og:description']??$meta['twitter:description']??$meta['description']??'';$image=$meta['og:image:secure_url']??$meta['og:image']??$meta['twitter:image']??$meta['twitter:image:src']??'';$site=$meta['og:site_name']??(string)(parse_url($url,PHP_URL_HOST)?:'');
        if($image!==''){$image=$this->resolveUrl($url,$image);try{$this->assertSafeUrl($image);}catch(RuntimeException){$image='';}}
        $favicon='';foreach($xp->query('//link[@href]')?:[] as $node){$rel=strtolower($node->getAttribute('rel'));if(str_contains($rel,'icon')){$favicon=$this->resolveUrl($url,$node->getAttribute('href'));break;}}if($favicon===''){$p=parse_url($url);$favicon=($p['scheme']??'https').'://'.($p['host']??'').'/favicon.ico';}try{$this->assertSafeUrl($favicon);}catch(RuntimeException){$favicon='';}
        $canonical=$url;$nodes=$xp->query('//link[contains(translate(@rel,"CANONICAL","canonical"),"canonical")]');if($nodes&&$nodes->length){$c=trim($nodes->item(0)->getAttribute('href'));if($c!==''){$c=$this->resolveUrl($url,$c);if(filter_var($c,FILTER_VALIDATE_URL))$canonical=$c;}}
        $host=strtolower((string)(parse_url($url,PHP_URL_HOST)?:''));$provider='';if(str_contains($host,'youtube.com')||$host==='youtu.be')$provider='YouTube';elseif(str_contains($host,'vimeo.com'))$provider='Vimeo';elseif($host==='github.com'||str_ends_with($host,'.github.com'))$provider='GitHub';
        $published=$meta['article:published_time']??$meta['date']??$meta['datepublished']??'';$publishedAt=$published!==''?(strtotime($published)?:null):null;
        return ['url'=>$canonical,'title'=>$this->cleanText($title,300),'description'=>$this->cleanText($desc,700),'image_url'=>DomainPolicy::imagesAllowed($url)?$image:'','favicon_url'=>$favicon,'site_name'=>$this->cleanText($site,150),'content_type'=>$ct,'provider'=>$provider,'author'=>$this->cleanText($meta['article:author']??$meta['author']??'',150),'section'=>$this->cleanText($meta['article:section']??'',150),'og_type'=>$this->cleanText($meta['og:type']??'',100),'locale'=>$this->cleanText($meta['og:locale']??'',50),'published_at'=>$publishedAt,'image_width'=>isset($meta['og:image:width'])?(int)$meta['og:image:width']:null,'image_height'=>isset($meta['og:image:height'])?(int)$meta['og:image:height']:null];
    }
    private function cleanText(string $t,int $max):string{$t=trim(preg_replace('/\s+/u',' ',strip_tags(html_entity_decode($t,ENT_QUOTES|ENT_HTML5,'UTF-8')))??'');return function_exists('mb_substr')?mb_substr($t,0,$max,'UTF-8'):substr($t,0,$max);}
    private function resolveUrl(string $base,string $rel):string{$rel=trim(html_entity_decode($rel,ENT_QUOTES|ENT_HTML5,'UTF-8'));if($rel===''||preg_match('~^https?://~i',$rel))return $rel;$bp=parse_url($base);if(!is_array($bp)||empty($bp['host']))return $rel;$scheme=$bp['scheme']??'https';$auth=$scheme.'://'.$bp['host'].(isset($bp['port'])?':'.$bp['port']:'');if(str_starts_with($rel,'//'))return $scheme.':'.$rel;if(str_starts_with($rel,'/'))return $auth.$rel;$dir=preg_replace('~/[^/]*$~','/',$bp['path']??'/')?:'/';$segs=[];foreach(explode('/',$dir.$rel) as $s){if($s===''||$s==='.')continue;if($s==='..')array_pop($segs);else$segs[]=$s;}return $auth.'/'.implode('/',$segs);}
    private function buildUrl(array $p):string{$u=$p['scheme'].'://';if(isset($p['user'])){$u.=$p['user'].(isset($p['pass'])?':'.$p['pass']:'').'@';}$u.=$p['host'];if(isset($p['port']))$u.=':'.$p['port'];$u.=$p['path']??'';if(isset($p['query']))$u.='?'.$p['query'];return $u;}
}
